# Generated by Django 4.1.2 on 2023-01-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_type_post_subtype_post_type_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
