# Generated by Django 3.2.2 on 2023-01-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, default='1234', max_length=20, null=True),
        ),
    ]
